version: "3"
services:
  rss_agg_pg_db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - rss-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s
  ####
  rss_agg_go_server:
    image: ${SERVER_IMAGE_URI}
    ports:
      - ${PORT}:${PORT}
    environment:
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@rss_agg_pg_db/${POSTGRES_DB}?sslmode=disable
      - PORT=${PORT}
    command:
      - /bin/bash
      - -c
      - |
        goose -dir /app/sql/schema postgres postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@rss_agg_pg_db/${POSTGRES_DB}?sslmode=disable up
        /app/go_rss_demo
    depends_on:
      rss_agg_pg_db:
        condition: service_healthy
volumes:
  rss-data:
    driver: local
